import {
  BARBARIAN,
  DRUID,
  FIGHTER,
  RANGER,
  BARD,
  WARLOCK,
  WIZARD,
  CLERIC,
  ROGUE,
} from '@/typings/class'
import type {
  Axe,
  SilverWeapon,
  CrystalBall,
  CyclopsVisionCrystal,
  ManaSphere,
  Sword,
  Polearm,
  Shield,
  Dagger,
  Staff,
  IceFang,
  Mace,
  Crossbow,
  CrystalSword,
  SovereignsGhostblade,
  LanternShield,
  Bow,
  Spellbook,
  GoldenWeapon,
  LightBringer,
  Grimslayer,
} from '@/typings/equip'

export const ARMING_SWORDS: Sword[] = [
  {
    name: 'Arming Sword',
    rarity: 0,
    src: new URL('@/assets/weapons/arming_sword/45px-Arming_Sword_1.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [29],
    class: [FIGHTER, RANGER, BARD],
  },
  {
    name: 'Arming Sword',
    rarity: 1,
    src: new URL('@/assets/weapons/arming_sword/45px-Arming_Sword_2.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [30, 31],
    class: [FIGHTER, RANGER, BARD],
  },
  {
    name: 'Arming Sword',
    rarity: 2,
    src: new URL('@/assets/weapons/arming_sword/45px-Arming_Sword_3.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [32, 33],
    class: [FIGHTER, RANGER, BARD],
  },
  {
    name: 'Arming Sword',
    rarity: 3,
    src: new URL('@/assets/weapons/arming_sword/45px-Arming_Sword_4.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [34, 35],
    class: [FIGHTER, RANGER, BARD],
  },
  {
    name: 'Arming Sword',
    rarity: 4,
    src: new URL('@/assets/weapons/arming_sword/45px-Arming_Sword_5.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [36, 37],
    class: [FIGHTER, RANGER, BARD],
  },
  {
    name: 'Arming Sword',
    rarity: 5,
    src: new URL('@/assets/weapons/arming_sword/45px-Arming_Sword_6.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [38, 39],
    class: [FIGHTER, RANGER, BARD],
  },
  {
    name: 'Arming Sword',
    rarity: 6,
    src: new URL("@/assets/weapons/arming_sword/45px-Kuma's_Claw.png", import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [40, 41],
    class: [FIGHTER, RANGER, BARD],
  },
]

export const BARDICHES: Polearm[] = [
  {
    name: 'Bardiche',
    rarity: 0,
    src: new URL('@/assets/weapons/bardiche/90px-Bardiche_1.png', import.meta.url),
    move_speed_reduction: 45,
    physical_weapon_damage: [48],
    class: [BARBARIAN, WARLOCK],
  },
  {
    name: 'Bardiche',
    rarity: 1,
    src: new URL('@/assets/weapons/bardiche/90px-Bardiche_2.png', import.meta.url),
    move_speed_reduction: 45,
    physical_weapon_damage: [49, 52],
    class: [BARBARIAN, WARLOCK],
  },
  {
    name: 'Bardiche',
    rarity: 2,
    src: new URL('@/assets/weapons/bardiche/90px-Bardiche_3.png', import.meta.url),
    move_speed_reduction: 45,
    physical_weapon_damage: [53, 56],
    class: [BARBARIAN, WARLOCK],
  },
  {
    name: 'Bardiche',
    rarity: 3,
    src: new URL('@/assets/weapons/bardiche/90px-Bardiche_4.png', import.meta.url),
    move_speed_reduction: 45,
    physical_weapon_damage: [57, 60],
    class: [BARBARIAN, WARLOCK],
  },
  {
    name: 'Bardiche',
    rarity: 4,
    src: new URL('@/assets/weapons/bardiche/90px-Bardiche_5.png', import.meta.url),
    move_speed_reduction: 45,
    physical_weapon_damage: [61, 64],
    class: [BARBARIAN, WARLOCK],
  },
  {
    name: 'Bardiche',
    rarity: 5,
    src: new URL('@/assets/weapons/bardiche/90px-Bardiche_6.png', import.meta.url),
    move_speed_reduction: 45,
    physical_weapon_damage: [65, 68],
    class: [BARBARIAN, WARLOCK],
  },
  {
    name: 'Bardiche',
    rarity: 6,
    src: new URL('@/assets/weapons/bardiche/90px-Bardiche_6.png', import.meta.url),
    move_speed_reduction: 45,
    physical_weapon_damage: [69, 72],
    class: [BARBARIAN, WARLOCK],
  },
]

export const BATTLE_AXES: Axe[] = [
  {
    name: 'Battle Axe',
    rarity: 0,
    src: new URL('@/assets/weapons/battle_axe/90px-Battle_Axe_1.png', import.meta.url),
    move_speed_reduction: 30,
    physical_weapon_damage: [48],
    class: [BARBARIAN, FIGHTER],
  },
  {
    name: 'Battle Axe',
    rarity: 1,
    src: new URL('@/assets/weapons/battle_axe/90px-Battle_Axe_2.png', import.meta.url),
    move_speed_reduction: 30,
    physical_weapon_damage: [49, 51],
    class: [BARBARIAN, FIGHTER],
  },
  {
    name: 'Battle Axe',
    rarity: 2,
    src: new URL('@/assets/weapons/battle_axe/90px-Battle_Axe_3.png', import.meta.url),
    move_speed_reduction: 30,
    physical_weapon_damage: [52, 55],
    class: [BARBARIAN, FIGHTER],
  },
  {
    name: 'Battle Axe',
    rarity: 3,
    src: new URL('@/assets/weapons/battle_axe/90px-Battle_Axe_4.png', import.meta.url),
    move_speed_reduction: 30,
    physical_weapon_damage: [56, 59],
    class: [BARBARIAN, FIGHTER],
  },
  {
    name: 'Battle Axe',
    rarity: 4,
    src: new URL('@/assets/weapons/battle_axe/90px-Battle_Axe_5.png', import.meta.url),
    move_speed_reduction: 30,
    physical_weapon_damage: [60, 61],
    class: [BARBARIAN, FIGHTER],
  },
  {
    name: 'Battle Axe',
    rarity: 5,
    src: new URL('@/assets/weapons/battle_axe/90px-Battle_Axe_6.png', import.meta.url),
    move_speed_reduction: 30,
    physical_weapon_damage: [62, 64],
    class: [BARBARIAN, FIGHTER],
  },
  {
    name: 'Echo of Screams',
    rarity: 6,
    src: new URL('@/assets/weapons/battle_axe/90px-Echo_of_Screams.png', import.meta.url),
    move_speed_reduction: 30,
    physical_weapon_damage: [66, 69],
    class: [BARBARIAN, FIGHTER],
  },
]

export const BUCKLERS: Shield[] = [
  {
    name: 'Buckler',
    rarity: 0,
    src: new URL('@/assets/weapons/buckler/90px-Buckler_1.png', import.meta.url),
    move_speed_reduction: 12,
    armor_rating: [17, 18],
    class: [CLERIC, FIGHTER, BARD],
  },
  {
    name: 'Buckler',
    rarity: 1,
    src: new URL('@/assets/weapons/buckler/90px-Buckler_2.png', import.meta.url),
    move_speed_reduction: 12,
    armor_rating: [19, 20],
    class: [CLERIC, FIGHTER, BARD],
  },
  {
    name: 'Buckler',
    rarity: 2,
    src: new URL('@/assets/weapons/buckler/90px-Buckler_3.png', import.meta.url),
    move_speed_reduction: 12,
    armor_rating: [21, 22],
    class: [CLERIC, FIGHTER, BARD],
  },
  {
    name: 'Buckler',
    rarity: 3,
    src: new URL('@/assets/weapons/buckler/90px-Buckler_4.png', import.meta.url),
    move_speed_reduction: 12,
    armor_rating: [23, 24],
    class: [CLERIC, FIGHTER, BARD],
  },
  {
    name: 'Buckler',
    rarity: 4,
    src: new URL('@/assets/weapons/buckler/90px-Buckler_5.png', import.meta.url),
    move_speed_reduction: 12,
    armor_rating: [25, 26],
    class: [CLERIC, FIGHTER, BARD],
  },
  {
    name: 'Buckler',
    rarity: 5,
    src: new URL('@/assets/weapons/buckler/90px-Buckler_6.png', import.meta.url),
    move_speed_reduction: 12,
    armor_rating: [27, 28],
    class: [CLERIC, FIGHTER, BARD],
  },
  {
    name: 'Buckler',
    rarity: 6,
    src: new URL('@/assets/weapons/buckler/90px-Delirium.png', import.meta.url),
    move_speed_reduction: 12,
    armor_rating: [29, 30],
    class: [CLERIC, FIGHTER, BARD],
  },
]

export const CASTILLION_DAGGERS: (Dagger | IceFang)[] = [
  {
    name: 'Castillon Dagger',
    rarity: 0,
    src: new URL('@/assets/weapons/castillon_dagger/45px-Castillon_Dagger_1.png', import.meta.url),
    move_speed_reduction: 30,
    physical_weapon_damage: [20],
    armor_penetration: 0,
    class: [ROGUE, FIGHTER, BARD, DRUID],
  },
  {
    name: 'Castillon Dagger',
    rarity: 1,
    src: new URL('@/assets/weapons/castillon_dagger/45px-Castillon_Dagger_2.png', import.meta.url),
    move_speed_reduction: 30,
    physical_weapon_damage: [21, 22],
    armor_penetration: 0,
    class: [ROGUE, FIGHTER, BARD, DRUID],
  },
  {
    name: 'Castillon Dagger',
    rarity: 2,
    src: new URL('@/assets/weapons/castillon_dagger/45px-Castillon_Dagger_3.png', import.meta.url),
    move_speed_reduction: 30,
    physical_weapon_damage: [23, 24],
    armor_penetration: 0,
    class: [ROGUE, FIGHTER, BARD, DRUID],
  },
  {
    name: 'Castillon Dagger',
    rarity: 3,
    src: new URL('@/assets/weapons/castillon_dagger/45px-Castillon_Dagger_4.png', import.meta.url),
    move_speed_reduction: 30,
    physical_weapon_damage: [25, 26],
    armor_penetration: 0,
    class: [ROGUE, FIGHTER, BARD, DRUID],
  },
  {
    name: 'Castillon Dagger',
    rarity: 4,
    src: new URL('@/assets/weapons/castillon_dagger/45px-Castillon_Dagger_5.png', import.meta.url),
    move_speed_reduction: 30,
    physical_weapon_damage: [27],
    armor_penetration: 0,
    class: [ROGUE, FIGHTER, BARD, DRUID],
  },
  {
    name: 'Castillon Dagger',
    rarity: 5,
    src: new URL('@/assets/weapons/castillon_dagger/45px-Castillon_Dagger_6.png', import.meta.url),
    move_speed_reduction: 30,
    physical_weapon_damage: [28],
    armor_penetration: 0,
    class: [ROGUE, FIGHTER, BARD, DRUID],
  },
  {
    name: 'Castillon Dagger',
    rarity: 6,
    src: new URL('@/assets/weapons/castillon_dagger/45px-Castillon_Dagger_6.png', import.meta.url),
    move_speed_reduction: 10,
    physical_weapon_damage: [29, 30],
    armor_penetration: 0,
    class: [ROGUE, FIGHTER, BARD, DRUID],
  },
  {
    name: 'Icefang',
    rarity: 4,
    src: new URL('@/assets/weapons/castillon_dagger/45px-Icefang.png', import.meta.url),
    move_speed_reduction: 10,
    physical_weapon_damage: [27],
    armor_penetration: 10,
    true_physical_damage: 1,
    class: [ROGUE, FIGHTER, BARD, DRUID],
  },
]

export const CEREMONIAL_STAFFS: Staff[] = [
  {
    name: 'Ceremonial Staff',
    rarity: 0,
    src: new URL('@/assets/weapons/ceremonial_staff/45px-Ceremonial_staff_2.png', import.meta.url),
    move_speed_reduction: 30,
    physical_weapon_damage: [23],
    magical_damage: 0,
    magic_penetration: 0,
    magical_healing: 1,
    class: [CLERIC, WIZARD, WARLOCK, DRUID],
  },
  {
    name: 'Ceremonial Staff',
    rarity: 1,
    src: new URL('@/assets/weapons/ceremonial_staff/45px-Ceremonial_staff_2.png', import.meta.url),
    move_speed_reduction: 30,
    physical_weapon_damage: [24, 25],
    magical_damage: 0,
    magic_penetration: 0,
    magical_healing: 2,
    class: [CLERIC, WIZARD, WARLOCK, DRUID],
  },
  {
    name: 'Ceremonial Staff',
    rarity: 2,
    src: new URL('@/assets/weapons/ceremonial_staff/45px-Ceremonial_staff_2.png', import.meta.url),
    move_speed_reduction: 30,
    physical_weapon_damage: [26, 28],
    magical_damage: 0,
    magic_penetration: 0,
    magical_healing: 3,
    class: [CLERIC, WIZARD, WARLOCK, DRUID],
  },
  {
    name: 'Ceremonial Staff',
    rarity: 3,
    src: new URL('@/assets/weapons/ceremonial_staff/45px-Ceremonial_staff_2.png', import.meta.url),
    move_speed_reduction: 30,
    physical_weapon_damage: [29, 30],
    magical_damage: 0,
    magic_penetration: 0,
    magical_healing: 4,
    class: [CLERIC, WIZARD, WARLOCK, DRUID],
  },
  {
    name: 'Ceremonial Staff',
    rarity: 4,
    src: new URL('@/assets/weapons/ceremonial_staff/45px-Ceremonial_staff_2.png', import.meta.url),
    move_speed_reduction: 30,
    physical_weapon_damage: [31],
    magical_damage: 0,
    magic_penetration: 0,
    magical_healing: 5,
    class: [CLERIC, WIZARD, WARLOCK, DRUID],
  },
  {
    name: 'Ceremonial Staff',
    rarity: 5,
    src: new URL('@/assets/weapons/ceremonial_staff/45px-Ceremonial_staff_2.png', import.meta.url),
    move_speed_reduction: 30,
    physical_weapon_damage: [32],
    magical_damage: 0,
    magic_penetration: 0,
    magical_healing: 6,
    class: [CLERIC, WIZARD, WARLOCK, DRUID],
  },
  {
    name: 'Ceremonial Staff',
    rarity: 6,
    src: new URL('@/assets/weapons/ceremonial_staff/45px-Ceremonial_staff_2.png', import.meta.url),
    move_speed_reduction: 30,
    physical_weapon_damage: [34, 35],
    magical_damage: 0,
    magic_penetration: 0,
    magical_healing: 7,
    class: [CLERIC, WIZARD, WARLOCK, DRUID],
  },
]

export const CLUBS: Mace[] = [
  {
    name: 'Club',
    rarity: 0,
    src: new URL('@/assets/weapons/club/45px-Club_2.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [28],
    armor_penetration: [10],
    class: [BARBARIAN],
  },
  {
    name: 'Club',
    rarity: 1,
    src: new URL('@/assets/weapons/club/45px-Club_2.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [29, 30],
    armor_penetration: [10],
    class: [BARBARIAN],
  },
  {
    name: 'Club',
    rarity: 2,
    src: new URL('@/assets/weapons/club/45px-Club_2.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [31, 32],
    armor_penetration: [10],
    class: [BARBARIAN],
  },
  {
    name: 'Club',
    rarity: 3,
    src: new URL('@/assets/weapons/club/45px-Club_2.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [33, 34],
    armor_penetration: [10],
    class: [BARBARIAN],
  },
  {
    name: 'Club',
    rarity: 4,
    src: new URL('@/assets/weapons/club/45px-Club_2.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [35],
    armor_penetration: [10],
    class: [BARBARIAN],
  },
  {
    name: 'Club',
    rarity: 5,
    src: new URL('@/assets/weapons/club/45px-Club_2.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [36],
    armor_penetration: [10],
    class: [BARBARIAN],
  },
  {
    name: 'Club',
    rarity: 6,
    src: new URL('@/assets/weapons/club/45px-Club_2.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [36],
    armor_penetration: [10],
    class: [BARBARIAN],
  },
  {
    name: 'Boneshaper',
    rarity: 5,
    src: new URL('@/assets/weapons/club/45px-Club_2.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [35],
    armor_penetration: [14, 15],
    class: [BARBARIAN],
  },
]

export const CROSSBOWS: Crossbow[] = [
  {
    name: 'Crossbow',
    rarity: 0,
    src: new URL('@/assets/weapons/crossbow/90px-Crossbow_1.png', import.meta.url),
    move_speed_reduction: 50,
    physical_weapon_damage: [36],
    armor_penetration: 30,
    class: [FIGHTER, RANGER, WIZARD, BARD],
  },
  {
    name: 'Crossbow',
    rarity: 1,
    src: new URL('@/assets/weapons/crossbow/90px-Crossbow_2.png', import.meta.url),
    move_speed_reduction: 50,
    physical_weapon_damage: [37, 39],
    armor_penetration: 30,
    class: [FIGHTER, RANGER, WIZARD, BARD],
  },
  {
    name: 'Crossbow',
    rarity: 2,
    src: new URL('@/assets/weapons/crossbow/90px-Crossbow_3.png', import.meta.url),
    move_speed_reduction: 50,
    physical_weapon_damage: [40, 42],
    armor_penetration: 30,
    class: [FIGHTER, RANGER, WIZARD, BARD],
  },
  {
    name: 'Crossbow',
    rarity: 3,
    src: new URL('@/assets/weapons/crossbow/90px-Crossbow_4.png', import.meta.url),
    move_speed_reduction: 50,
    physical_weapon_damage: [43, 44],
    armor_penetration: 30,
    class: [FIGHTER, RANGER, WIZARD, BARD],
  },
  {
    name: 'Crossbow',
    rarity: 4,
    src: new URL('@/assets/weapons/crossbow/90px-Crossbow_5.png', import.meta.url),
    move_speed_reduction: 50,
    physical_weapon_damage: [45],
    armor_penetration: 30,
    class: [FIGHTER, RANGER, WIZARD, BARD],
  },
  {
    name: 'Crossbow',
    rarity: 5,
    src: new URL('@/assets/weapons/crossbow/90px-Crossbow_6.png', import.meta.url),
    move_speed_reduction: 50,
    physical_weapon_damage: [46],
    armor_penetration: 30,
    class: [FIGHTER, RANGER, WIZARD, BARD],
  },
  {
    name: 'Crossbow',
    rarity: 6,
    src: new URL('@/assets/weapons/crossbow/90px-Crossbow_6.png', import.meta.url),
    move_speed_reduction: 50,
    physical_weapon_damage: [49, 52],
    armor_penetration: 30,
    class: [FIGHTER, RANGER, WIZARD, BARD],
  },
]

export const CRYSTAL_BALLS: (CrystalBall | CyclopsVisionCrystal | ManaSphere)[] = [
  {
    name: 'Crystal Ball',
    rarity: 0,
    src: new URL('@/assets/weapons/crystal_ball/90px-Crystal_Ball_1.png', import.meta.url),
    move_speed_reduction: 15,
    magical_damage: 2,
    addition_physical_weapon_damage: 1,
    magic_penetration: 10,
    class: [WIZARD, WARLOCK, DRUID],
  },
  {
    name: 'Crystal Ball',
    rarity: 1,
    src: new URL('@/assets/weapons/crystal_ball/90px-Crystal_Ball_2.png', import.meta.url),
    move_speed_reduction: 15,
    magical_damage: 3,
    addition_physical_weapon_damage: 1,
    magic_penetration: 10,
    class: [WIZARD, WARLOCK, DRUID],
  },
  {
    name: 'Crystal Ball',
    rarity: 2,
    src: new URL('@/assets/weapons/crystal_ball/90px-Crystal_Ball_3.png', import.meta.url),
    move_speed_reduction: 15,
    magical_damage: 4,
    addition_physical_weapon_damage: 2,
    magic_penetration: 10,
    class: [WIZARD, WARLOCK, DRUID],
  },
  {
    name: 'Crystal Ball',
    rarity: 3,
    src: new URL('@/assets/weapons/crystal_ball/90px-Crystal_Ball_4.png', import.meta.url),
    move_speed_reduction: 15,
    magical_damage: 5,
    addition_physical_weapon_damage: 2,
    magic_penetration: 10,
    class: [WIZARD, WARLOCK, DRUID],
  },
  {
    name: 'Crystal Ball',
    rarity: 4,
    src: new URL('@/assets/weapons/crystal_ball/90px-Crystal_Ball_5.png', import.meta.url),
    move_speed_reduction: 15,
    magical_damage: 6,
    addition_physical_weapon_damage: 2,
    magic_penetration: 10,
    class: [WIZARD, WARLOCK, DRUID],
  },
  {
    name: 'Crystal Ball',
    rarity: 5,
    src: new URL('@/assets/weapons/crystal_ball/90px-Crystal_Ball_6.png', import.meta.url),
    move_speed_reduction: 15,
    magical_damage: 7,
    addition_physical_weapon_damage: 3,
    magic_penetration: 10,
    class: [WIZARD, WARLOCK, DRUID],
  },
  {
    name: "Zirkzi's Eye",
    rarity: 6,
    src: new URL("@/assets/weapons/crystal_ball/90px-Zirkzi's_Eye.png", import.meta.url),
    move_speed_reduction: 15,
    magical_damage: 8,
    addition_physical_weapon_damage: 3,
    magic_penetration: 10,
    class: [WIZARD, WARLOCK, DRUID],
  },
  {
    name: 'Cyclops Vision Crystal',
    rarity: 4,
    src: new URL('@/assets/weapons/crystal_ball/90px-Cyclops_Vision_Crystal.png', import.meta.url),
    move_speed_reduction: 15,
    magical_damage: 6,
    addition_physical_weapon_damage: 2,
    magic_penetration: 10,
    dexterity: 2,
    strength: 2,
    knowledge: 2,
    class: [WIZARD, WARLOCK, DRUID],
  },
  {
    name: 'Mana Sphere',
    rarity: 4,
    src: new URL('@/assets/weapons/crystal_ball/90px-Mana_Sphere.png', import.meta.url),
    move_speed_reduction: 15,
    magical_damage: 6,
    addition_physical_weapon_damage: 2,
    true_magical_damage: [1, 2],
    magic_penetration: 10,
    will: 2,
    knowledge: 2,
    class: [WIZARD, WARLOCK, DRUID],
  },
]

export const CRYSTAL_SWORDS: (CrystalSword | SovereignsGhostblade)[] = [
  {
    name: 'Crystal Sword',
    rarity: 0,
    src: new URL('@/assets/weapons/crystal_sword/45px-Crystal_Sword_1.png', import.meta.url),
    move_speed_reduction: 25,
    physical_weapon_damage: [12],
    magical_weapon_damage: [12],
    class: [WIZARD, WARLOCK],
  },
  {
    name: 'Crystal Sword',
    rarity: 1,
    src: new URL('@/assets/weapons/crystal_sword/45px-Crystal_Sword_2.png', import.meta.url),
    move_speed_reduction: 25,
    physical_weapon_damage: [13, 14],
    magical_weapon_damage: [13, 14],
    class: [WIZARD, WARLOCK],
  },
  {
    name: 'Crystal Sword',
    rarity: 2,
    src: new URL('@/assets/weapons/crystal_sword/45px-Crystal_Sword_3.png', import.meta.url),
    move_speed_reduction: 25,
    physical_weapon_damage: [15, 16],
    magical_weapon_damage: [15, 16],
    class: [WIZARD, WARLOCK],
  },
  {
    name: 'Crystal Sword',
    rarity: 3,
    src: new URL('@/assets/weapons/crystal_sword/45px-Crystal_Sword_4.png', import.meta.url),
    move_speed_reduction: 25,
    physical_weapon_damage: [17, 18],
    magical_weapon_damage: [17, 18],
    class: [WIZARD, WARLOCK],
  },
  {
    name: 'Crystal Sword',
    rarity: 4,
    src: new URL('@/assets/weapons/crystal_sword/45px-Crystal_Sword_5.png', import.meta.url),
    move_speed_reduction: 25,
    physical_weapon_damage: [19],
    magical_weapon_damage: [19],
    class: [WIZARD, WARLOCK],
  },
  {
    name: 'Crystal Sword',
    rarity: 5,
    src: new URL('@/assets/weapons/crystal_sword/45px-Crystal_Sword_6.png', import.meta.url),
    move_speed_reduction: 25,
    physical_weapon_damage: [20],
    magical_weapon_damage: [20],
    class: [WIZARD, WARLOCK],
  },
  {
    name: 'Crystal Sword',
    rarity: 6,
    src: new URL('@/assets/weapons/crystal_sword/45px-Crystal_Sword_6.png', import.meta.url),
    move_speed_reduction: 25,
    physical_weapon_damage: [21, 22],
    magical_weapon_damage: [21, 22],
    class: [WIZARD, WARLOCK],
  },
  {
    name: 'Frostlight Crystal Sword',
    rarity: 4,
    src: new URL(
      '@/assets/weapons/crystal_sword/45px-Frostlight_Crystal_Sword.png',
      import.meta.url,
    ),
    move_speed_reduction: 21,
    physical_weapon_damage: [19],
    magical_weapon_damage: [19],
    class: [WIZARD, WARLOCK],
  },
  {
    name: "Sovereign's Ghostblade",
    rarity: 4,
    src: new URL("@/assets/weapons/crystal_sword/45px-Sovereign's_Ghostblade.png", import.meta.url),
    move_speed_reduction: 25,
    physical_weapon_damage: [19],
    magical_weapon_damage: [19],
    move_speed_bonus: 2,
    magical_healing: 2,
    class: [WIZARD, WARLOCK],
  },
]

export const DOUBLE_AXES: (Axe | SilverWeapon)[] = [
  {
    name: 'Double Axe',
    rarity: 0,
    src: new URL('@/assets/weapons/double_axe/90px-Double_Axe_1.png', import.meta.url),
    move_speed_reduction: 35,
    physical_weapon_damage: [51],
    class: [BARBARIAN],
  },
  {
    name: 'Double Axe',
    rarity: 1,
    src: new URL('@/assets/weapons/double_axe/90px-Double_Axe_2.png', import.meta.url),
    move_speed_reduction: 35,
    physical_weapon_damage: [52, 54],
    class: [BARBARIAN],
  },
  {
    name: 'Double Axe',
    rarity: 2,
    src: new URL('@/assets/weapons/double_axe/90px-Double_Axe_3.png', import.meta.url),
    move_speed_reduction: 35,
    physical_weapon_damage: [55, 57],
    class: [BARBARIAN],
  },
  {
    name: 'Double Axe',
    rarity: 3,
    src: new URL('@/assets/weapons/double_axe/90px-Double_Axe_4.png', import.meta.url),
    move_speed_reduction: 35,
    physical_weapon_damage: [58, 60],
    class: [BARBARIAN],
  },
  {
    name: 'Double Axe',
    rarity: 4,
    src: new URL('@/assets/weapons/double_axe/90px-Double_Axe_5.png', import.meta.url),
    move_speed_reduction: 35,
    physical_weapon_damage: [61, 63],
    class: [BARBARIAN],
  },
  {
    name: 'Double Axe',
    rarity: 5,
    src: new URL('@/assets/weapons/double_axe/90px-Double_Axe_6.png', import.meta.url),
    move_speed_reduction: 35,
    physical_weapon_damage: [64, 66],
    class: [BARBARIAN],
  },
  {
    name: 'Life After Death',
    rarity: 6,
    src: new URL('@/assets/weapons/double_axe/90px-Life_after_Death.png', import.meta.url),
    move_speed_reduction: 35,
    physical_weapon_damage: [68, 70],
    class: [BARBARIAN],
  },
  {
    name: 'Sterling Axe',
    rarity: 2,
    src: new URL('@/assets/weapons/double_axe/90px-Sterling_Axe.png', import.meta.url),
    move_speed_reduction: 35,
    undead_damage_bonus: 15,
    physical_weapon_damage: [52, 55],
    class: [BARBARIAN],
  },
  {
    name: 'Axe of Righteousness',
    rarity: 3,
    src: new URL('@/assets/weapons/double_axe/90px-Axe_of_Righteousness.png', import.meta.url),
    move_speed_reduction: 35,
    undead_damage_bonus: 15,
    physical_weapon_damage: [56, 59],
    class: [BARBARIAN],
  },
  {
    name: 'Divine Axe',
    rarity: 4,
    src: new URL('@/assets/weapons/double_axe/90px-Divine_Axe.png', import.meta.url),
    move_speed_reduction: 35,
    undead_damage_bonus: 15,
    physical_weapon_damage: [60, 62],
    class: [BARBARIAN],
  },
]

export const FALCHIONS: Sword[] = [
  {
    name: 'Falchion',
    rarity: 0,
    src: new URL('@/assets/weapons/falchion/45px-Falchion_1.png', import.meta.url),
    move_speed_reduction: 25,
    physical_weapon_damage: [35],
    class: [FIGHTER, BARD, WARLOCK],
  },
  {
    name: 'Falchion',
    rarity: 1,
    src: new URL('@/assets/weapons/falchion/45px-Falchion_2.png', import.meta.url),
    move_speed_reduction: 25,
    physical_weapon_damage: [36, 37],
    class: [FIGHTER, BARD, WARLOCK],
  },
  {
    name: 'Falchion',
    rarity: 2,
    src: new URL('@/assets/weapons/falchion/45px-Falchion_3.png', import.meta.url),
    move_speed_reduction: 25,
    physical_weapon_damage: [38, 39],
    class: [FIGHTER, BARD, WARLOCK],
  },
  {
    name: 'Falchion',
    rarity: 3,
    src: new URL('@/assets/weapons/falchion/45px-Falchion_4.png', import.meta.url),
    move_speed_reduction: 25,
    physical_weapon_damage: [40, 41],
    class: [FIGHTER, BARD, WARLOCK],
  },
  {
    name: 'Falchion',
    rarity: 4,
    src: new URL('@/assets/weapons/falchion/45px-Falchion_5.png', import.meta.url),
    move_speed_reduction: 25,
    physical_weapon_damage: [42, 43],
    class: [FIGHTER, BARD, WARLOCK],
  },
  {
    name: 'Falchion',
    rarity: 5,
    src: new URL('@/assets/weapons/falchion/45px-Falchion_6.png', import.meta.url),
    move_speed_reduction: 25,
    physical_weapon_damage: [44, 45],
    class: [FIGHTER, BARD, WARLOCK],
  },
  {
    name: "Kuma's Fang",
    rarity: 0,
    src: new URL("@/assets/weapons/falchion/45px-Kuma's_Fang.png", import.meta.url),
    move_speed_reduction: 25,
    physical_weapon_damage: [46, 47],
    class: [FIGHTER, BARD, WARLOCK],
  },
  {
    name: 'Falchion of Honor',
    rarity: 0,
    src: new URL('@/assets/weapons/falchion/45px-Falchion_of_Honor.png', import.meta.url),
    move_speed_reduction: 25,
    physical_weapon_damage: [42, 43],
    class: [FIGHTER, BARD, WARLOCK],
  },
]

export const FELLING_AXES: (Axe | GoldenWeapon)[] = [
  {
    name: 'Felling Axe',
    rarity: 0,
    src: new URL('@/assets/weapons/felling_axe/90px-Felling_Axe_1.png', import.meta.url),
    move_speed_reduction: 30,
    physical_weapon_damage: [41],
    class: [BARBARIAN],
  },
  {
    name: 'Felling Axe',
    rarity: 1,
    src: new URL('@/assets/weapons/felling_axe/90px-Felling_Axe_2.png', import.meta.url),
    move_speed_reduction: 30,
    physical_weapon_damage: [43, 46],
    class: [BARBARIAN],
  },
  {
    name: 'Felling Axe',
    rarity: 2,
    src: new URL('@/assets/weapons/felling_axe/90px-Felling_Axe_3.png', import.meta.url),
    move_speed_reduction: 30,
    physical_weapon_damage: [47, 49],
    class: [BARBARIAN],
  },
  {
    name: 'Felling Axe',
    rarity: 3,
    src: new URL('@/assets/weapons/felling_axe/90px-Felling_Axe_4.png', import.meta.url),
    move_speed_reduction: 30,
    physical_weapon_damage: [50, 52],
    class: [BARBARIAN],
  },
  {
    name: 'Felling Axe',
    rarity: 4,
    src: new URL('@/assets/weapons/felling_axe/90px-Felling_Axe_5.png', import.meta.url),
    move_speed_reduction: 30,
    physical_weapon_damage: [53, 54],
    class: [BARBARIAN],
  },
  {
    name: 'Felling Axe',
    rarity: 5,
    src: new URL('@/assets/weapons/felling_axe/90px-Felling_Axe_6.png', import.meta.url),
    move_speed_reduction: 30,
    physical_weapon_damage: [55],
    class: [BARBARIAN],
  },
  {
    name: 'Soulscraper',
    rarity: 6,
    src: new URL('@/assets/weapons/felling_axe/90px-Soulscraper.png', import.meta.url),
    move_speed_reduction: 30,
    physical_weapon_damage: [57, 59],
    class: [BARBARIAN],
  },
  {
    name: 'Golden Felling Axe',
    rarity: 4,
    src: new URL('@/assets/weapons/felling_axe/90px-Golden_Felling_Axe.png', import.meta.url),
    move_speed_reduction: 30,
    physical_weapon_damage: [53, 54],
    luck: 10,
    magical_damage_reduction: 1.5,
    class: [BARBARIAN],
  },
]

export const FLANGED_MACES: (Mace | SilverWeapon | LightBringer)[] = [
  {
    name: 'Flanged Mace',
    rarity: 0,
    src: new URL('@/assets/weapons/flanged_mace/45px-Flanged_Mace_1.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [33],
    armor_penetration: [15],
    class: [FIGHTER, CLERIC, DRUID],
  },
  {
    name: 'Flanged Mace',
    rarity: 1,
    src: new URL('@/assets/weapons/flanged_mace/45px-Flanged_Mace_2.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [34, 35],
    armor_penetration: [15],
    class: [FIGHTER, CLERIC, DRUID],
  },
  {
    name: 'Flanged Mace',
    rarity: 2,
    src: new URL('@/assets/weapons/flanged_mace/45px-Flanged_Mace_3.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [36, 37],
    armor_penetration: [15],
    class: [FIGHTER, CLERIC, DRUID],
  },
  {
    name: 'Flanged Mace',
    rarity: 3,
    src: new URL('@/assets/weapons/flanged_mace/45px-Flanged_Mace_4.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [38, 39],
    armor_penetration: [15],
    class: [FIGHTER, CLERIC, DRUID],
  },
  {
    name: 'Flanged Mace',
    rarity: 4,
    src: new URL('@/assets/weapons/flanged_mace/45px-Flanged_Mace_5.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [40],
    armor_penetration: [15],
    class: [FIGHTER, CLERIC, DRUID],
  },
  {
    name: 'Flanged Mace',
    rarity: 5,
    src: new URL('@/assets/weapons/flanged_mace/45px-Flanged_Mace_6.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [41],
    armor_penetration: [15],
    class: [FIGHTER, CLERIC, DRUID],
  },
  {
    name: 'Flanged Mace',
    rarity: 6,
    src: new URL('@/assets/weapons/flanged_mace/45px-Flanged_Mace_6.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [43, 44],
    armor_penetration: [15],
    class: [FIGHTER, CLERIC, DRUID],
  },
  {
    name: 'Light Bringer',
    rarity: 4,
    src: new URL('@/assets/weapons/flanged_mace/45px-Light_Bringer.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [40],
    armor_penetration: [15],
    action_speed: [3, 4],
    class: [FIGHTER, CLERIC, DRUID],
  },
  {
    name: 'Sterling Rod',
    rarity: 1,
    src: new URL('@/assets/weapons/flanged_mace/45px-Sterling_Rod.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [34, 35],
    armor_penetration: [15],
    undead_damage_bonus: 15,
    class: [FIGHTER, CLERIC, DRUID],
  },
  {
    name: 'Rod of Righteousness',
    rarity: 2,
    src: new URL('@/assets/weapons/flanged_mace/45px-Rod_of_Righteousness.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [36, 37],
    armor_penetration: [15],
    undead_damage_bonus: 15,
    class: [FIGHTER, CLERIC, DRUID],
  },
  {
    name: 'Divine Rod',
    rarity: 3,
    src: new URL('@/assets/weapons/flanged_mace/45px-Divine_Rod.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [38, 39],
    armor_penetration: [15],
    undead_damage_bonus: 15,
    class: [FIGHTER, CLERIC, DRUID],
  },
]

export const HALBERDS: Polearm[] = [
  {
    name: 'Halberd',
    rarity: 0,
    src: new URL('@/assets/weapons/halberd/90px-Halberd_1.png', import.meta.url),
    move_speed_reduction: 45,
    physical_weapon_damage: [51],
    class: [FIGHTER, WARLOCK],
  },
  {
    name: 'Halberd',
    rarity: 1,
    src: new URL('@/assets/weapons/halberd/90px-Halberd_2.png', import.meta.url),
    move_speed_reduction: 45,
    physical_weapon_damage: [52, 54],
    class: [FIGHTER, WARLOCK],
  },
  {
    name: 'Halberd',
    rarity: 2,
    src: new URL('@/assets/weapons/halberd/90px-Halberd_3.png', import.meta.url),
    move_speed_reduction: 45,
    physical_weapon_damage: [56, 58],
    class: [FIGHTER, WARLOCK],
  },
  {
    name: 'Halberd',
    rarity: 3,
    src: new URL('@/assets/weapons/halberd/90px-Halberd_4.png', import.meta.url),
    move_speed_reduction: 45,
    physical_weapon_damage: [60, 62],
    class: [FIGHTER, WARLOCK],
  },
  {
    name: 'Halberd',
    rarity: 4,
    src: new URL('@/assets/weapons/halberd/90px-Halberd_5.png', import.meta.url),
    move_speed_reduction: 45,
    physical_weapon_damage: [64, 66],
    class: [FIGHTER, WARLOCK],
  },
  {
    name: 'Halberd',
    rarity: 5,
    src: new URL('@/assets/weapons/halberd/90px-Halberd_6.png', import.meta.url),
    move_speed_reduction: 45,
    physical_weapon_damage: [67, 69],
    class: [FIGHTER, WARLOCK],
  },
  {
    name: 'Cinder',
    rarity: 6,
    src: new URL('@/assets/weapons/halberd/90px-Cinder.png', import.meta.url),
    move_speed_reduction: 45,
    physical_weapon_damage: [71, 74],
    class: [FIGHTER, WARLOCK],
  },
]

export const HAND_CROSSBOWS: Crossbow[] = [
  {
    name: 'Hand Crossbow',
    rarity: 0,
    src: new URL('@/assets/weapons/hand_crossbow/90px-Hand_Crossbow_1.png', import.meta.url),
    move_speed_reduction: 25,
    physical_weapon_damage: [18],
    armor_penetration: 5,
    class: [ROGUE, RANGER, BARD],
  },
  {
    name: 'Hand Crossbow',
    rarity: 1,
    src: new URL('@/assets/weapons/hand_crossbow/90px-Hand_Crossbow_2.png', import.meta.url),
    move_speed_reduction: 25,
    physical_weapon_damage: [19, 20],
    armor_penetration: 5,
    class: [ROGUE, RANGER, BARD],
  },
  {
    name: 'Hand Crossbow',
    rarity: 2,
    src: new URL('@/assets/weapons/hand_crossbow/90px-Hand_Crossbow_3.png', import.meta.url),
    move_speed_reduction: 25,
    physical_weapon_damage: [20, 21],
    armor_penetration: 5,
    class: [ROGUE, RANGER, BARD],
  },
  {
    name: 'Hand Crossbow',
    rarity: 3,
    src: new URL('@/assets/weapons/hand_crossbow/90px-Hand_Crossbow_4.png', import.meta.url),
    move_speed_reduction: 25,
    physical_weapon_damage: [21, 22],
    armor_penetration: 5,
    class: [ROGUE, RANGER, BARD],
  },
  {
    name: 'Hand Crossbow',
    rarity: 4,
    src: new URL('@/assets/weapons/hand_crossbow/90px-Hand_Crossbow_5.png', import.meta.url),
    move_speed_reduction: 25,
    physical_weapon_damage: [23],
    armor_penetration: 5,
    class: [ROGUE, RANGER, BARD],
  },
  {
    name: 'Hand Crossbow',
    rarity: 5,
    src: new URL('@/assets/weapons/hand_crossbow/90px-Hand_Crossbow_6.png', import.meta.url),
    move_speed_reduction: 25,
    physical_weapon_damage: [24],
    armor_penetration: 5,
    class: [ROGUE, RANGER, BARD],
  },
  {
    name: 'Hand Crossbow',
    rarity: 6,
    src: new URL('@/assets/weapons/hand_crossbow/90px-Hand_Crossbow_6.png', import.meta.url),
    move_speed_reduction: 25,
    physical_weapon_damage: [25, 26],
    armor_penetration: 5,
    class: [ROGUE, RANGER, BARD],
  },
]

export const HATCHETS: Axe[] = [
  {
    name: 'Hatchet',
    rarity: 0,
    src: new URL('@/assets/weapons/hatchet/45px-Hatchet_1.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [27],
    class: [FIGHTER, BARBARIAN],
  },
  {
    name: 'Hatchet',
    rarity: 1,
    src: new URL('@/assets/weapons/hatchet/45px-Hatchet_2.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [28, 30],
    class: [FIGHTER, BARBARIAN],
  },
  {
    name: 'Hatchet',
    rarity: 2,
    src: new URL('@/assets/weapons/hatchet/45px-Hatchet_3.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [31, 33],
    class: [FIGHTER, BARBARIAN],
  },
  {
    name: 'Hatchet',
    rarity: 3,
    src: new URL('@/assets/weapons/hatchet/45px-Hatchet_4.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [34, 36],
    class: [FIGHTER, BARBARIAN],
  },
  {
    name: 'Hatchet',
    rarity: 4,
    src: new URL('@/assets/weapons/hatchet/45px-Hatchet_5.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [37, 39],
    class: [FIGHTER, BARBARIAN],
  },
  {
    name: 'Hatchet',
    rarity: 5,
    src: new URL('@/assets/weapons/hatchet/45px-Hatchet_6.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [40, 42],
    class: [FIGHTER, BARBARIAN],
  },
  {
    name: 'Hatchet',
    rarity: 6,
    src: new URL('@/assets/weapons/hatchet/45px-Hatchet_6.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage: [43, 45],
    class: [FIGHTER, BARBARIAN],
  },
]

export const HEATER_SHIELDS: Shield[] = [
  {
    name: 'Heater Shield',
    rarity: 0,
    src: new URL('@/assets/weapons/heater_shield/90px-Heater_Shield_1.png', import.meta.url),
    move_speed_reduction: 20,
    armor_rating: [20, 21],
    class: [CLERIC, FIGHTER, WARLOCK],
  },
  {
    name: 'Heater Shield',
    rarity: 1,
    src: new URL('@/assets/weapons/heater_shield/90px-Heater_Shield_2.png', import.meta.url),
    move_speed_reduction: 20,
    armor_rating: [22, 23],
    class: [CLERIC, FIGHTER, WARLOCK],
  },
  {
    name: 'Heater Shield',
    rarity: 2,
    src: new URL('@/assets/weapons/heater_shield/90px-Heater_Shield_3.png', import.meta.url),
    move_speed_reduction: 20,
    armor_rating: [24, 26],
    class: [CLERIC, FIGHTER, WARLOCK],
  },
  {
    name: 'Heater Shield',
    rarity: 3,
    src: new URL('@/assets/weapons/heater_shield/90px-Heater_Shield_4.png', import.meta.url),
    move_speed_reduction: 20,
    armor_rating: [27, 29],
    class: [CLERIC, FIGHTER, WARLOCK],
  },
  {
    name: 'Heater Shield',
    rarity: 4,
    src: new URL('@/assets/weapons/heater_shield/90px-Heater_Shield_5.png', import.meta.url),
    move_speed_reduction: 20,
    armor_rating: [30, 32],
    class: [CLERIC, FIGHTER, WARLOCK],
  },
  {
    name: 'Heater Shield',
    rarity: 5,
    src: new URL('@/assets/weapons/heater_shield/90px-Heater_Shield_6.png', import.meta.url),
    move_speed_reduction: 20,
    armor_rating: [33, 35],
    class: [CLERIC, FIGHTER, WARLOCK],
  },
  {
    name: 'Aegis',
    rarity: 6,
    src: new URL('@/assets/weapons/heater_shield/90px-Aegis.png', import.meta.url),
    move_speed_reduction: 20,
    armor_rating: [36, 38],
    class: [CLERIC, FIGHTER, WARLOCK],
  },
]

export const HORSEMANS_AXES: Axe[] = [
  {
    name: "Horseman's Axe",
    rarity: 0,
    src: new URL("@/assets/weapons/horsemans_axe/45px-Horseman's_Axe_1.png", import.meta.url),
    move_speed_reduction: 22,
    physical_weapon_damage: [29],
    class: [FIGHTER, BARBARIAN],
  },
  {
    name: "Horseman's Axe",
    rarity: 1,
    src: new URL("@/assets/weapons/horsemans_axe/45px-Horseman's_Axe_2.png", import.meta.url),
    move_speed_reduction: 22,
    physical_weapon_damage: [30, 32],
    class: [FIGHTER, BARBARIAN],
  },
  {
    name: "Horseman's Axe",
    rarity: 2,
    src: new URL("@/assets/weapons/horsemans_axe/45px-Horseman's_Axe_3.png", import.meta.url),
    move_speed_reduction: 22,
    physical_weapon_damage: [33, 35],
    class: [FIGHTER, BARBARIAN],
  },
  {
    name: "Horseman's Axe",
    rarity: 3,
    src: new URL("@/assets/weapons/horsemans_axe/45px-Horseman's_Axe_4.png", import.meta.url),
    move_speed_reduction: 22,
    physical_weapon_damage: [36, 38],
    class: [FIGHTER, BARBARIAN],
  },
  {
    name: "Horseman's Axe",
    rarity: 4,
    src: new URL("@/assets/weapons/horsemans_axe/45px-Horseman's_Axe_5.png", import.meta.url),
    move_speed_reduction: 22,
    physical_weapon_damage: [39, 41],
    class: [FIGHTER, BARBARIAN],
  },
  {
    name: "Horseman's Axe",
    rarity: 5,
    src: new URL("@/assets/weapons/horsemans_axe/45px-Horseman's_Axe_6.png", import.meta.url),
    move_speed_reduction: 22,
    physical_weapon_damage: [42, 44],
    class: [FIGHTER, BARBARIAN],
  },
  {
    name: 'Famine',
    rarity: 6,
    src: new URL('@/assets/weapons/horsemans_axe/45px-Famine.png', import.meta.url),
    move_speed_reduction: 22,
    physical_weapon_damage: [45, 47],
    class: [FIGHTER, BARBARIAN],
  },
]

export const KRIS_DAGGERS: Dagger[] = [
  {
    name: 'Kris Dagger',
    rarity: 0,
    src: new URL('@/assets/weapons/kris_dagger/45px-Kris_Dagger_1.png', import.meta.url),
    move_speed_reduction: 10,
    physical_weapon_damage: [20],
    armor_penetration: 0,
    class: [FIGHTER, BARBARIAN],
  },
  {
    name: 'Kris Dagger',
    rarity: 1,
    src: new URL('@/assets/weapons/kris_dagger/45px-Kris_Dagger_2.png', import.meta.url),
    move_speed_reduction: 10,
    physical_weapon_damage: [21, 22],
    armor_penetration: 0,
    class: [FIGHTER, BARBARIAN],
  },
  {
    name: 'Kris Dagger',
    rarity: 2,
    src: new URL('@/assets/weapons/kris_dagger/45px-Kris_Dagger_3.png', import.meta.url),
    move_speed_reduction: 10,
    physical_weapon_damage: [23, 24],
    armor_penetration: 0,
    class: [FIGHTER, BARBARIAN],
  },
  {
    name: 'Kris Dagger',
    rarity: 3,
    src: new URL('@/assets/weapons/kris_dagger/45px-Kris_Dagger_4.png', import.meta.url),
    move_speed_reduction: 10,
    physical_weapon_damage: [24, 25],
    armor_penetration: 0,
    class: [FIGHTER, BARBARIAN],
  },
  {
    name: 'Kris Dagger',
    rarity: 4,
    src: new URL('@/assets/weapons/kris_dagger/45px-Kris_Dagger_5.png', import.meta.url),
    move_speed_reduction: 10,
    physical_weapon_damage: [26],
    armor_penetration: 0,
    class: [FIGHTER, BARBARIAN],
  },
  {
    name: 'Kris Dagger',
    rarity: 5,
    src: new URL('@/assets/weapons/kris_dagger/45px-Kris_Dagger_6.png', import.meta.url),
    move_speed_reduction: 10,
    physical_weapon_damage: [27],
    armor_penetration: 0,
    class: [FIGHTER, BARBARIAN],
  },
  {
    name: 'Kris Dagger',
    rarity: 6,
    src: new URL('@/assets/weapons/kris_dagger/45px-Kris_Dagger_6.png', import.meta.url),
    move_speed_reduction: 10,
    physical_weapon_damage: [28, 29],
    armor_penetration: 0,
    class: [FIGHTER, BARBARIAN],
  },
]

export const LANTERN_SHIELDS: LanternShield[] = []

export const LONGBOWS: Bow[] = []

export const LONGSWORDS: (Sword | SilverWeapon)[] = []

export const MAGIC_STAFFS: Staff[] = []

export const MORNING_STARS: Mace[] = []

export const PAVISES: Shield[] = []

export const QUARTERSTAFFS: (Mace | SilverWeapon)[] = []

export const RAPIERS: Sword[] = []

export const RECURVE_BOWS: (Bow | SilverWeapon)[] = []

export const RONDEL_DAGGERS: (Dagger | SilverWeapon)[] = []

export const ROUND_SHIELDS: Shield[] = []

export const SPEARS: Polearm[] = []

export const SPELLBOOKS: Spellbook[] = []

export const STILETTO_DAGGERS: Dagger[] = []

export const SURVIVAL_BOWS: Bow[] = []

export const VIKING_SWORDS: (Sword | GoldenWeapon)[] = []

export const WAR_HAMMERS: Mace[] = []

export const WAR_MAULs: Mace[] = []

export const WINDLASS_CROSSBOWS: Crossbow[] = []

export const ZWEIHANDERS: (Sword | Grimslayer)[] = []
