import { BARBARIAN, DRUID, FIGHTER, RANGER, BARD, WARLOCK, WIZARD } from '@/typings/class'
import type {
  Axe,
  SilverWeapon,
  CrystalBall,
  CyclopsVisionCrystal,
  ManaSphere,
  Sword,
  Polearm,
  Shield,
  Dagger,
  Staff,
  IceFang,
} from '@/typings/equip'

export const ARMING_SWORDS: Sword[] = [
  {
    name: 'Arming Sword',
    rarity: 0,
    src: new URL('@/assets/weapons/arming_sword/45px-Arming_Sword_1.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage_low: 29,
    physical_weapon_damage_high: 29,
    class: [FIGHTER, RANGER, BARD],
  },
  {
    name: 'Arming Sword',
    rarity: 1,
    src: new URL('@/assets/weapons/arming_sword/45px-Arming_Sword_2.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage_low: 30,
    physical_weapon_damage_high: 31,
    class: [FIGHTER, RANGER, BARD],
  },
  {
    name: 'Arming Sword',
    rarity: 2,
    src: new URL('@/assets/weapons/arming_sword/45px-Arming_Sword_3.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage_low: 32,
    physical_weapon_damage_high: 33,
    class: [FIGHTER, RANGER, BARD],
  },
  {
    name: 'Arming Sword',
    rarity: 3,
    src: new URL('@/assets/weapons/arming_sword/45px-Arming_Sword_4.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage_low: 34,
    physical_weapon_damage_high: 35,
    class: [FIGHTER, RANGER, BARD],
  },
  {
    name: 'Arming Sword',
    rarity: 4,
    src: new URL('@/assets/weapons/arming_sword/45px-Arming_Sword_5.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage_low: 36,
    physical_weapon_damage_high: 37,
    class: [FIGHTER, RANGER, BARD],
  },
  {
    name: 'Arming Sword',
    rarity: 5,
    src: new URL('@/assets/weapons/arming_sword/45px-Arming_Sword_6.png', import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage_low: 38,
    physical_weapon_damage_high: 39,
    class: [FIGHTER, RANGER, BARD],
  },
  {
    name: 'Arming Sword',
    rarity: 7,
    src: new URL("@/assets/weapons/arming_sword/45px-Kuma's_Claw.png", import.meta.url),
    move_speed_reduction: 20,
    physical_weapon_damage_low: 40,
    physical_weapon_damage_high: 41,
    class: [FIGHTER, RANGER, BARD],
  },
]

export const BARDICHES: Polearm[] = [
  {
    name: 'Bardiche',
    rarity: 0,
    src: new URL('@/assets/weapons/bardiche/90px-Bardiche_1.png', import.meta.url),
    move_speed_reduction: 45,
    physical_weapon_damage_low: 48,
    physical_weapon_damage_high: 48,
    class: [BARBARIAN, WARLOCK],
  },
  {
    name: 'Bardiche',
    rarity: 1,
    src: new URL('@/assets/weapons/bardiche/90px-Bardiche_2.png', import.meta.url),
    move_speed_reduction: 45,
    physical_weapon_damage_low: 49,
    physical_weapon_damage_high: 52,
    class: [BARBARIAN, WARLOCK],
  },
  {
    name: 'Bardiche',
    rarity: 2,
    src: new URL('@/assets/weapons/bardiche/90px-Bardiche_3.png', import.meta.url),
    move_speed_reduction: 45,
    physical_weapon_damage_low: 53,
    physical_weapon_damage_high: 56,
    class: [BARBARIAN, WARLOCK],
  },
  {
    name: 'Bardiche',
    rarity: 3,
    src: new URL('@/assets/weapons/bardiche/90px-Bardiche_4.png', import.meta.url),
    move_speed_reduction: 45,
    physical_weapon_damage_low: 57,
    physical_weapon_damage_high: 60,
    class: [BARBARIAN, WARLOCK],
  },
  {
    name: 'Bardiche',
    rarity: 4,
    src: new URL('@/assets/weapons/bardiche/90px-Bardiche_5.png', import.meta.url),
    move_speed_reduction: 45,
    physical_weapon_damage_low: 61,
    physical_weapon_damage_high: 64,
    class: [BARBARIAN, WARLOCK],
  },
  {
    name: 'Bardiche',
    rarity: 5,
    src: new URL('@/assets/weapons/bardiche/90px-Bardiche_6.png', import.meta.url),
    move_speed_reduction: 45,
    physical_weapon_damage_low: 65,
    physical_weapon_damage_high: 68,
    class: [BARBARIAN, WARLOCK],
  },
  {
    name: 'Bardiche',
    rarity: 6,
    src: new URL('@/assets/weapons/bardiche/90px-Bardiche_6.png', import.meta.url),
    move_speed_reduction: 45,
    physical_weapon_damage_low: 69,
    physical_weapon_damage_high: 72,
    class: [BARBARIAN, WARLOCK],
  },
]

export const BATTLE_AXES: Axe[] = []

export const BUCKLERS: Shield[] = []

export const CASTILLION_DAGGERS: (Dagger | IceFang)[] = []

export const CEREMONIAL_STAFFS: Staff[] = []

export const DOUBLE_AXES: (Axe | SilverWeapon)[] = [
  {
    name: 'Double Axe',
    rarity: 0,
    src: new URL('@/assets/weapons/double_axe/90px-Double_Axe_1.png', import.meta.url),
    move_speed_reduction: 35,
    physical_weapon_damage_low: 51,
    physical_weapon_damage_high: 51,
    class: [BARBARIAN],
  },
  {
    name: 'Double Axe',
    rarity: 1,
    src: new URL('@/assets/weapons/double_axe/90px-Double_Axe_2.png', import.meta.url),
    move_speed_reduction: 35,
    physical_weapon_damage_low: 52,
    physical_weapon_damage_high: 54,
    class: [BARBARIAN],
  },
  {
    name: 'Double Axe',
    rarity: 2,
    src: new URL('@/assets/weapons/double_axe/90px-Double_Axe_3.png', import.meta.url),
    move_speed_reduction: 35,
    physical_weapon_damage_low: 55,
    physical_weapon_damage_high: 57,
    class: [BARBARIAN],
  },
  {
    name: 'Double Axe',
    rarity: 3,
    src: new URL('@/assets/weapons/double_axe/90px-Double_Axe_4.png', import.meta.url),
    move_speed_reduction: 35,
    physical_weapon_damage_low: 58,
    physical_weapon_damage_high: 60,
    class: [BARBARIAN],
  },
  {
    name: 'Double Axe',
    rarity: 4,
    src: new URL('@/assets/weapons/double_axe/90px-Double_Axe_5.png', import.meta.url),
    move_speed_reduction: 35,
    physical_weapon_damage_low: 61,
    physical_weapon_damage_high: 63,
    class: [BARBARIAN],
  },
  {
    name: 'Double Axe',
    rarity: 5,
    src: new URL('@/assets/weapons/double_axe/90px-Double_Axe_6.png', import.meta.url),
    move_speed_reduction: 35,
    physical_weapon_damage_low: 64,
    physical_weapon_damage_high: 66,
    class: [BARBARIAN],
  },
  {
    name: 'Life After Death',
    rarity: 6,
    src: new URL('@/assets/weapons/double_axe/90px-Life_after_Death.png', import.meta.url),
    move_speed_reduction: 35,
    physical_weapon_damage_low: 68,
    physical_weapon_damage_high: 70,
    class: [BARBARIAN],
  },
  {
    name: 'Sterling Axe',
    rarity: 2,
    src: new URL('@/assets/weapons/double_axe/90px-Sterling_Axe.png', import.meta.url),
    move_speed_reduction: 35,
    undead_damage_bonus: 15,
    physical_weapon_damage_low: 52,
    physical_weapon_damage_high: 55,
    class: [BARBARIAN],
  },
  {
    name: 'Axe of Righteousness',
    rarity: 3,
    src: new URL('@/assets/weapons/double_axe/90px-Axe_of_Righteousness.png', import.meta.url),
    move_speed_reduction: 35,
    undead_damage_bonus: 15,
    physical_weapon_damage_low: 56,
    physical_weapon_damage_high: 59,
    class: [BARBARIAN],
  },
  {
    name: 'Divine Axe',
    rarity: 4,
    src: new URL('@/assets/weapons/double_axe/90px-Divine_Axe.png', import.meta.url),
    move_speed_reduction: 35,
    undead_damage_bonus: 15,
    physical_weapon_damage_low: 60,
    physical_weapon_damage_high: 62,
    class: [BARBARIAN],
  },
]

export const CRYSTAL_BALLS: (CrystalBall | CyclopsVisionCrystal | ManaSphere)[] = [
  {
    name: 'Crystal Ball',
    rarity: 0,
    src: new URL('@/assets/weapons/crystal_ball/90px-Crystal_Ball_1.png', import.meta.url),
    move_speed_reduction: 15,
    magical_damage: 2,
    addition_physical_weapon_damage: 1,
    magic_penetration: 10,
    class: [WIZARD, WARLOCK, DRUID],
  },
  {
    name: 'Crystal Ball',
    rarity: 1,
    src: new URL('@/assets/weapons/crystal_ball/90px-Crystal_Ball_2.png', import.meta.url),
    move_speed_reduction: 15,
    magical_damage: 3,
    addition_physical_weapon_damage: 1,
    magic_penetration: 10,
    class: [WIZARD, WARLOCK, DRUID],
  },
  {
    name: 'Crystal Ball',
    rarity: 2,
    src: new URL('@/assets/weapons/crystal_ball/90px-Crystal_Ball_3.png', import.meta.url),
    move_speed_reduction: 15,
    magical_damage: 4,
    addition_physical_weapon_damage: 2,
    magic_penetration: 10,
    class: [WIZARD, WARLOCK, DRUID],
  },
  {
    name: 'Crystal Ball',
    rarity: 3,
    src: new URL('@/assets/weapons/crystal_ball/90px-Crystal_Ball_4.png', import.meta.url),
    move_speed_reduction: 15,
    magical_damage: 5,
    addition_physical_weapon_damage: 2,
    magic_penetration: 10,
    class: [WIZARD, WARLOCK, DRUID],
  },
  {
    name: 'Crystal Ball',
    rarity: 4,
    src: new URL('@/assets/weapons/crystal_ball/90px-Crystal_Ball_5.png', import.meta.url),
    move_speed_reduction: 15,
    magical_damage: 6,
    addition_physical_weapon_damage: 2,
    magic_penetration: 10,
    class: [WIZARD, WARLOCK, DRUID],
  },
  {
    name: 'Crystal Ball',
    rarity: 5,
    src: new URL('@/assets/weapons/crystal_ball/90px-Crystal_Ball_6.png', import.meta.url),
    move_speed_reduction: 15,
    magical_damage: 7,
    addition_physical_weapon_damage: 3,
    magic_penetration: 10,
    class: [WIZARD, WARLOCK, DRUID],
  },
  {
    name: "Zirkzi's Eye",
    rarity: 6,
    src: new URL("@/assets/weapons/crystal_ball/90px-Zirkzi's_Eye.png", import.meta.url),
    move_speed_reduction: 15,
    magical_damage: 8,
    addition_physical_weapon_damage: 3,
    magic_penetration: 10,
    class: [WIZARD, WARLOCK, DRUID],
  },
  {
    name: 'Cyclops Vision Crystal',
    rarity: 4,
    src: new URL('@/assets/weapons/crystal_ball/90px-Cyclops_Vision_Crystal.png', import.meta.url),
    move_speed_reduction: 15,
    magical_damage: 6,
    addition_physical_weapon_damage: 2,
    magic_penetration: 10,
    dexterity: 2,
    strength: 2,
    knowledge: 2,
    class: [WIZARD, WARLOCK, DRUID],
  },
  {
    name: 'Mana Sphere',
    rarity: 4,
    src: new URL('@/assets/weapons/crystal_ball/90px-Mana_Sphere.png', import.meta.url),
    move_speed_reduction: 15,
    magical_damage: 6,
    addition_physical_weapon_damage: 2,
    true_magical_damage_low: 1,
    true_magical_damage_high: 2,
    magic_penetration: 10,
    will: 2,
    knowledge: 2,
    class: [WIZARD, WARLOCK, DRUID],
  },
]
