import { BARBARIAN, DRUID, WARLOCK, WIZARD } from '@/typings/class'
import type {
  DoubleAxe,
  SilverWeapon,
  CrystalBall,
  CyclopsVisionCrystal,
  ManaSphere,
} from '@/typings/equip'

export const DOUBLE_AXES: (DoubleAxe | SilverWeapon)[] = [
  {
    name: 'Double Axe',
    rarity: 0,
    src: new URL('/public/assets/weapons/double_axe/90px-Double_Axe_1.png', import.meta.url),
    move_speed_reduction: 35,
    physical_weapon_damage_low: 51,
    physical_weapon_damage_high: 51,
    class: [BARBARIAN],
  },
  {
    name: 'Double Axe',
    rarity: 1,
    src: new URL('/public/assets/weapons/double_axe/90px-Double_Axe_2.png', import.meta.url),
    move_speed_reduction: 35,
    physical_weapon_damage_low: 52,
    physical_weapon_damage_high: 54,
    class: [BARBARIAN],
  },
  {
    name: 'Double Axe',
    rarity: 2,
    src: new URL('/public/assets/weapons/double_axe/90px-Double_Axe_3.png', import.meta.url),
    move_speed_reduction: 35,
    physical_weapon_damage_low: 55,
    physical_weapon_damage_high: 57,
    class: [BARBARIAN],
  },
  {
    name: 'Double Axe',
    rarity: 3,
    src: new URL('/public/assets/weapons/double_axe/90px-Double_Axe_4.png', import.meta.url),
    move_speed_reduction: 35,
    physical_weapon_damage_low: 58,
    physical_weapon_damage_high: 60,
    class: [BARBARIAN],
  },
  {
    name: 'Double Axe',
    rarity: 4,
    src: new URL('/public/assets/weapons/double_axe/90px-Double_Axe_5.png', import.meta.url),
    move_speed_reduction: 35,
    physical_weapon_damage_low: 61,
    physical_weapon_damage_high: 63,
    class: [BARBARIAN],
  },
  {
    name: 'Double Axe',
    rarity: 5,
    src: new URL('/public/assets/weapons/double_axe/90px-Double_Axe_6.png', import.meta.url),
    move_speed_reduction: 35,
    physical_weapon_damage_low: 64,
    physical_weapon_damage_high: 66,
    class: [BARBARIAN],
  },
  {
    name: 'Life After Death',
    rarity: 6,
    src: new URL('/public/assets/weapons/double_axe/90px-Life_after_Death.png', import.meta.url),
    move_speed_reduction: 35,
    physical_weapon_damage_low: 68,
    physical_weapon_damage_high: 70,
    class: [BARBARIAN],
  },
  {
    name: 'Sterling Axe',
    rarity: 2,
    src: new URL('/public/assets/weapons/double_axe/90px-Sterling_Axe.png', import.meta.url),
    move_speed_reduction: 35,
    undead_damage_bonus: 15,
    physical_weapon_damage_low: 52,
    physical_weapon_damage_high: 55,
    class: [BARBARIAN],
  },
  {
    name: 'Axe of Righteousness',
    rarity: 3,
    src: new URL(
      '/public/assets/weapons/double_axe/90px-Axe_of_Righteousness.png',
      import.meta.url,
    ),
    move_speed_reduction: 35,
    undead_damage_bonus: 15,
    physical_weapon_damage_low: 56,
    physical_weapon_damage_high: 59,
    class: [BARBARIAN],
  },
  {
    name: 'Divine Axe',
    rarity: 4,
    src: new URL('/public/assets/weapons/double_axe/90px-Divine_Axe.png', import.meta.url),
    move_speed_reduction: 35,
    undead_damage_bonus: 15,
    physical_weapon_damage_low: 60,
    physical_weapon_damage_high: 62,
    class: [BARBARIAN],
  },
]

export const CRYSTAL_BALLS: (CrystalBall | CyclopsVisionCrystal | ManaSphere)[] = [
  {
    name: 'Crystal Ball',
    rarity: 0,
    src: new URL('/public/assets/weapons/crystal_ball/90px-Crystal_Ball_1.png', import.meta.url),
    move_speed_reduction: 15,
    magical_damage: 2,
    addition_physical_weapon_damage: 1,
    magic_penetration: 10,
    class: [WIZARD, WARLOCK, DRUID],
  },
  {
    name: 'Crystal Ball',
    rarity: 1,
    src: new URL('/public/assets/weapons/crystal_ball/90px-Crystal_Ball_2.png', import.meta.url),
    move_speed_reduction: 15,
    magical_damage: 3,
    addition_physical_weapon_damage: 1,
    magic_penetration: 10,
    class: [WIZARD, WARLOCK, DRUID],
  },
  {
    name: 'Crystal Ball',
    rarity: 2,
    src: new URL('/public/assets/weapons/crystal_ball/90px-Crystal_Ball_3.png', import.meta.url),
    move_speed_reduction: 15,
    magical_damage: 4,
    addition_physical_weapon_damage: 2,
    magic_penetration: 10,
    class: [WIZARD, WARLOCK, DRUID],
  },
  {
    name: 'Crystal Ball',
    rarity: 3,
    src: new URL('/public/assets/weapons/crystal_ball/90px-Crystal_Ball_4.png', import.meta.url),
    move_speed_reduction: 15,
    magical_damage: 5,
    addition_physical_weapon_damage: 2,
    magic_penetration: 10,
    class: [WIZARD, WARLOCK, DRUID],
  },
  {
    name: 'Crystal Ball',
    rarity: 4,
    src: new URL('/public/assets/weapons/crystal_ball/90px-Crystal_Ball_5.png', import.meta.url),
    move_speed_reduction: 15,
    magical_damage: 6,
    addition_physical_weapon_damage: 2,
    magic_penetration: 10,
    class: [WIZARD, WARLOCK, DRUID],
  },
  {
    name: 'Crystal Ball',
    rarity: 5,
    src: new URL('/public/assets/weapons/crystal_ball/90px-Crystal_Ball_6.png', import.meta.url),
    move_speed_reduction: 15,
    magical_damage: 7,
    addition_physical_weapon_damage: 3,
    magic_penetration: 10,
    class: [WIZARD, WARLOCK, DRUID],
  },
  {
    name: "Zirkzi's Eye",
    rarity: 6,
    src: new URL("/public/assets/weapons/crystal_ball/90px-Zirkzi's_Eye.png", import.meta.url),
    move_speed_reduction: 15,
    magical_damage: 8,
    addition_physical_weapon_damage: 3,
    magic_penetration: 10,
    class: [WIZARD, WARLOCK, DRUID],
  },
  {
    name: 'Cyclops Vision Crystal',
    rarity: 4,
    src: new URL(
      '/public/assets/weapons/crystal_ball/90px-Cyclops_Vision_Crystal.png',
      import.meta.url,
    ),
    move_speed_reduction: 15,
    magical_damage: 6,
    addition_physical_weapon_damage: 2,
    magic_penetration: 10,
    dexterity: 2,
    strength: 2,
    knowledge: 2,
    class: [WIZARD, WARLOCK, DRUID],
  },
  {
    name: 'Mana Sphere',
    rarity: 4,
    src: new URL('/public/assets/weapons/crystal_ball/90px-Mana_Sphere.png', import.meta.url),
    move_speed_reduction: 15,
    magical_damage: 6,
    addition_physical_weapon_damage: 2,
    true_magical_damage_low: 1,
    true_magical_damage_high: 2,
    magic_penetration: 10,
    will: 2,
    knowledge: 2,
    class: [WIZARD, WARLOCK, DRUID],
  },
]
