export type Class =
  | 'Wizard'
  | 'Druid'
  | 'Fighter'
  | 'Cleric'
  | 'Warlock'
  | 'Ranger'
  | 'Barbarian'
  | 'Rogue'
  | 'Bard'

export const WIZARD = 'Wizard'
export const DRUID = 'Druid'
export const FIGHTER = 'Fighter'
export const CLERIC = 'Cleric'
export const WARLOCK = 'Warlock'
export const RANGER = 'Ranger'
export const BARBARIAN = 'Barbarian'
export const ROGUE = 'Rogue'
export const BARD = 'Bard'
