export type Slot =
  | 'One Handed Main-Hand'
  | 'Two Handed Main-Hand'
  | 'One Handed Off-Hand'
  | 'Head'
  | 'Chest'
  | 'Legs'
  | 'Hands'
  | 'Feet'

export const ONEMAIN = 'One Handed Main-Hand'
export const TWOMAIN = 'One Handed Main-Hand'
export const ONEOFF = 'One Handed Off-Hand'
export const HEAD = 'Head'
export const CHEST = 'Chest'
export const LEGS = 'Legs'
export const HANDS = 'Hands'
export const FEET = 'Feet'
export const CLOAK = 'Cloak'
export const NECKLACE = 'Necklace'
export const RING = 'Ring'

export const WEAPON = 'Weapon'
export const ARMOR = 'Armor'
export const ACCESSORIES = 'Accessories'
